feat: add first implementation
gemini-testing/testplane-test-filter pull request #2
Opened 2018-07-31 15:33 UTC by rostik404

/cc @j0tunn @DudaGod @eGavr

2018-08-01 10:39 UTC, sipayRT requested changes

2018-08-01 10:39 UTC, sipayRT commented on lib/index.js
> +        console.info('Reports are not found. Tests will not run.');
это неправильная логика - если не нашли отчеты, то нужно запускать все тесты (т.е. не трогать дерево тестов вообще)

2018-08-01 10:39 UTC, sipayRT commented on lib/index.js
> +        reports = _.flatten(await readReports(pluginConfig.reportsPath));
давай flatten делать в readReports, чтобы здесь вообще не задумываться над форматом данных

2018-08-01 10:39 UTC, sipayRT commented on lib/config.js
> +        reportsPath: option({
почему это именно reportS?

2018-08-01 10:39 UTC, sipayRT commented on lib/config.js
> +                    throw new Error(`"reportsPath" option must be string, but got ${typeof v}`);
у тебя даже в сообщении есть намек на то, что мы можем передать только один отчет

2018-08-01 10:39 UTC, sipayRT commented on lib/index.js
> +        reports = _.flatten(await readReports(pluginConfig.reportsPath));
но если я правильно понял, то нам вообще этого не нужно делать, т.к. мы можем передать только один путь к данным

2018-08-01 10:39 UTC, sipayRT commented on lib/index.js
> +                testCollection.enableTest(title, [browser]);
если в доке указано `enableTest(fullTitle, [browserId])`, то это значит, что второй аргумент не обязательный :) 

как оно у тебя сейчас работает?

2018-08-01 10:39 UTC, sipayRT commented on lib/index.js
> +            try {
а для чего ты все в `try/catch` оборачиваешь? судя по коду, тест просто не найдется в дереве и не включится, никакой ошибки там не будет

2018-08-01 10:39 UTC, sipayRT commented on test/index.js
> +    it('should disable all tests before enabling', async () => {
а для чего этот тест? ты тут проверяешь середину действия, которая сама по себе ни к чему не приводит

2018-08-01 10:39 UTC, sipayRT commented on test/index.js
> +    it('should disable all tests before enabling', async () => {
а, ты этим хотел проверить свою логику, при которой ты хотел отключать все тесты, если не нашли ни один отчет?

2018-08-01 10:39 UTC, sipayRT commented on test/index.js
> +        testCollection.enableTest.withArgs('some-title', ['some-browser']).throws('some-err');
вот такого кейса не должно быть в реальном использовании апи включения тестов

2018-08-01 10:39 UTC, sipayRT commented on test/index.js
> +    it('should not enable tests if reports are not found', async () => {
по новой логике (запуск всех тестов, если отчетов нет) этого теста не должно быть

2018-08-01 10:40 UTC, sipayRT commented
и я так и не понял как оно у тебя не падало при передаче браузера массивом

2018-08-01 17:21 UTC, DudaGod requested changes

2018-08-01 17:21 UTC, DudaGod commented on README.md
> -# hermione-test-filter
Ростик нужно не забыть в package.json изменить `description` и `repository.url`

2018-08-01 17:21 UTC, DudaGod commented on README.md
> +Запускает определенные тесты в определенных браузерах, которые указаны в `json`-отчетах
фильтрует?

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +const globExtra = require('glob-extra');
Ростик, давай пакеты сортировать по ~~пиздатости~~ крутости )

2018-08-01 17:21 UTC, DudaGod commented on README.md
> +        enabled: false // by default
запятую бы после `false`

2018-08-01 17:21 UTC, DudaGod commented on README.md
> +        reportsPath: 'some/path/*.json' // path to reports with tests to run
не хочешь опции отдельно расписать? Типа обязательные/не обязательные и т.д.

2018-08-01 17:21 UTC, DudaGod commented on README.md
> +## Подключение
воу-воу, это же внешний пакет. Давай по английски писать. Например "Подключение" переводится как "Connection".

2018-08-01 17:21 UTC, DudaGod commented on lib/config.js
> +        reportsPath: option({
+1, я больше за `reportPath`

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +const globExtra = require('glob-extra');
Го так писать:
```js
const {expandPaths} = require('glob-extra');
```

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +        console.info('Reports are not found. Tests will not run.');
ростик признался мне, что хочет где-то здесь модуль `debug` юзнуть

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +    const reportsPaths = await globExtra.expandPaths(paths);
я бы переменную назвал `reportFilePaths`

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +    return Promise.map(reportsPaths, (p) => fs.readJson(p));
```js
return Promise.map(reportsPaths, fs.readJson);
```

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +    hermione.on(hermione.events.INIT, async () => {
у тебя же сейчас отчеты будут читаться и в воркерах и в мастере. Давай их читать только в мастере

2018-08-01 17:21 UTC, DudaGod commented on lib/index.js
> +    hermione.on(hermione.events.AFTER_TESTS_READ, (testCollection) => {
это событие летит и в воркерах и в мастере. Давай это делать только в мастере

2018-08-01 17:21 UTC, DudaGod commented on test/index.js
> +    };
обычно мы хелперы выше пишем, чем `beforeEach` и `afterEach`

2018-08-01 17:21 UTC, DudaGod commented on test/index.js
> +describe('test filter', () => {
тут еще нужно тесты разбить на master - worker

2018-08-01 19:10 UTC, rostik404 commented on lib/config.js
> +        reportsPath: option({
Ну вообще, это маска же, а по маске может находится несколько отчетов. Поэтому и множественное число

2018-08-01 20:41 UTC, rostik404 commented on lib/index.js
> +        reports = _.flatten(await readReports(pluginConfig.reportsPath));
Нужно, там же глоб, который маски раскрывает и находится несколько отчетов

2018-08-01 20:43 UTC, rostik404 commented on lib/index.js
> +const globExtra = require('glob-extra');
`glob-extra` - самый крутой)

2018-08-02 12:46 UTC, sipayRT approved these changes
в остальном ок

2018-08-02 12:46 UTC, sipayRT commented on README.md
> +* `reportsPath` **[String]** (optional, `hermione-*.json` by default) - path to reports with tests to run.
расскажи людям, что это не просто строка, а маска

2018-08-02 12:46 UTC, sipayRT commented on lib/config.js
> +                    throw new Error(`"reportsPath" option must be string, but got ${typeof v}`);
в сообщении должно быть упоминание, что это маска

2018-08-02 12:46 UTC, sipayRT commented on test/index.js
> +    describe('in master process of hermione', () => {
чет не нашел тест про самое главное - про то, что у тебя ТОЛЬКО КОНКРЕТНЫЕ тесты запускаются
т.е. у тебя есть 10 тестов, а включить ты должен только 2.и нужно проверить, что остальные 8 не запустятся

2018-08-02 17:10 UTC, rostik404 commented on test/index.js
> +    describe('in master process of hermione', () => {
@sipayRT, предлагаю просто в [этот тест](https://github.com/gemini-testing/hermione-test-filter/pull/2/files#diff-910eb6f57886ca16c136101fb1699231R66) добавить проверку, что позвался `disableAll` и `enableTest` позвался дважды. По-другому не вижу, как эту логику еще можно проверить.

2018-08-02 20:22 UTC, DudaGod commented on README.md
> -# hermione-test-filter
Ростик, ты так и не поправил =(

2018-08-02 20:22 UTC, DudaGod commented on README.md
> +It filters some tests from `hermione`-sets and only tests from `json`-reports will be run.
Зачем так сложно то? Я бы проще написал:
```js
Plugin for [hermione](https://github.com/gemini-testing/hermione) to filter tests specified in `json`-reports.
```

2018-08-02 20:22 UTC, DudaGod commented on README.md
> +
`## Configuration`

Кстати логичнее было бы, сначала описать конфигурация, а уже потом использование

2018-08-02 20:22 UTC, DudaGod commented on README.md
> +* `enabled` **[Boolean]** (optional, `false` by default) - Indicates whether the plugin needs to be started.
Почему не написать: `enable/disable the plugin`?

2018-08-02 20:22 UTC, DudaGod commented on lib/index.js
> +    return _.flatten(await Promise.map(reportFilePaths, (p) => fs.readJson(p)));
так а чего так не юзнул - `Promise.map(reportFilePaths, fs.readJson)`?

2018-08-02 20:22 UTC, DudaGod commented on lib/index.js
> +    return _.flatten(await Promise.map(reportFilePaths, (p) => fs.readJson(p)));
так а чего так не юзнул - `Promise.map(reportFilePaths, fs.readJson)`?

2018-08-02 20:22 UTC, DudaGod commented on lib/index.js
> +        if (hermione.isWorker()) {
Ростик зачем ты каждым воркером тут на `INIT` и ниже на `AFTER_TESTS_READ` подписываешься, чтобы потом внутри подписки просто выйти?

Выйди выше - до подписок

2018-08-02 20:22 UTC, DudaGod commented on lib/index.js
> +    return _.flatten(await Promise.map(reportFilePaths, (p) => fs.readJson(p)));
так а чего так не юзнул - `Promise.map(reportFilePaths, fs.readJson)`?

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +    const sandbox = sinon.createSandbox();
🔥

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +            assert.notCalled(testCollection.enableTest);
давай тут проверять, что ты вообще воркером не подписался ни на что. Примерно так:
```js
sandbox.spy(hermione, 'on');

await initHermione(hermione, {reportsPath: 'some/path'});

assert.notCalled(hermione.on);
```

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +            }]);
вот эти все стабы в этом тесте тебе не нужны же, ты раньше выходишь

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +            const testCollection = mkTestCollectionStub({isWorker: false});
`isWorker` нужно в другой метод передать - `mkHermioneStub`

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +            hermione.emit(hermione.events['AFTER_TESTS_READ'], testCollection);
`hermione.events.AFTER_TESTS_READ`
и ниже, короче ведь запись

2018-08-02 20:22 UTC, DudaGod commented on test/index.js
> +    describe('in master process of hermione', () => {
Да, вариант Ростика норм. Давайте так проверим.

2018-08-03 06:44 UTC, rostik404 commented on README.md
> +* `enabled` **[Boolean]** (optional, `false` by default) - Indicates whether the plugin needs to be started.
Обсудили голосом, что не заработает

2018-08-03 06:57 UTC, rostik404 commented on lib/index.js
> +    return _.flatten(await Promise.map(reportFilePaths, (p) => fs.readJson(p)));
Обсудили голосом, что не заработает

2018-08-03 08:59 UTC, merged