Add order sensitivity
gemini-testing/testplane-test-filter pull request #7
Opened 2019-02-04 13:11 UTC by ruslankhh

2019-02-05 08:44 UTC, ruslankhh commented
@miripiruni @rostik404 @sipayRT @Flackus посмотрите, пожалуйста.

2019-02-06 15:11 UTC, sipayRT requested changes
Я вообще не понимаю почему сортировку ты пытаешься делать именно в этом плагине - для его запуска ты ведь должен иметь файл с описанными тестами

2019-02-06 15:11 UTC, sipayRT commented on lib/helpers.js
> +const raiseUpTest = function(fullTitle, browserId) {
твой хелпер совсем не хелпер - он полностью зависит от переданного контекста. При этом, умеет он работать только с контекстом `testCollection`

2019-02-06 15:11 UTC, sipayRT commented on lib/helpers.js
> +        const idx = this._findTestIndex(fullTitle, browserId);
**нельзя** использовать приватные методы `testCollection`!

2019-02-06 15:11 UTC, sipayRT commented on lib/helpers.js
> +            this._specs[browserId].unshift(test);
у тебя же здесь по твоей логике реализован обычный reverse, не? (про приватные методы я уже написал)

2019-02-06 15:11 UTC, sipayRT commented on lib/index.js
> +        input.reverse().forEach(({fullTitle, browserId}) => {
для чего здесь reverse? там же просто массив объектов, который ревертнется, а ты в хелпере ревертнешь тесты обратно

2019-02-06 16:35 UTC, ruslankhh commented on lib/helpers.js
> +        const idx = this._findTestIndex(fullTitle, browserId);
Это я знаю) Как лучше тогда это сделать? Слать PR в hermione?

2019-02-06 16:38 UTC, ruslankhh commented on lib/helpers.js
> +const raiseUpTest = function(fullTitle, browserId) {
я не знал как это лучше назвать) по хорошему, это нужно в hermione унести.

2019-02-06 16:41 UTC, ruslankhh commented on lib/helpers.js
> +            this._specs[browserId].unshift(test);
Нет, не обычный.
У нас есть два массива: список всех тестов с данными и фильтр.
Нужно сматчить тесты из одного массива по другому, и положить их в том же порядке, что и в фильтре на верх массива со всеми тестами. При этом другие тесты должны остаться)

2019-02-06 16:44 UTC, ruslankhh commented on lib/index.js
> +        input.reverse().forEach(({fullTitle, browserId}) => {
Если затереть весь `this._originalSpecs` и `this._specs`, то да, можно так сделать. Но я не затирваю.

2019-02-06 16:47 UTC, ruslankhh commented on lib/helpers.js
> +const raiseUpTest = function(fullTitle, browserId) {
Я в принципе вынес это, с наметкой на то, чтобы это унести в hermione.

2019-02-06 16:49 UTC, ruslankhh commented
@sipayRT
> Я вообще не понимаю почему сортировку ты пытаешься делать именно в этом плагине - для его запуска ты ведь должен иметь файл с описанными тестами.
> файл с описанными тестами.
Это ты про что? Про `hermione-test-filter`? Так он так и работает, с этим файлом, изначально.

2019-02-07 07:45 UTC, sipayRT commented
> Это ты про что? Про `hermione-test-filter.json`? Так он так и работает, с этим файлом, изначально.

да, я про него - ты постоянно будешь использовать файл с данными, чтобы указать порядок выполнения тестов?

2019-02-07 16:29 UTC, ruslankhh commented
да

2019-02-11 07:18 UTC, ruslankhh commented
/ping

2019-02-13 07:51 UTC, ruslankhh commented
/stop

2019-02-13 09:30 UTC, closed without merging