Add filtering tests by their code
gemini-testing/testplane-test-filter pull request #8
Opened 2020-06-02 09:25 UTC by ruslankhh

2020-06-02 09:27 UTC, ruslankhh commented on test/index.js
> +        it('should run all tests if all options is empty', async () => {
Здесь дифф у gitHub криво построился. Я прост перенёс этот тест на верх, а другие сгруппировал по опциям.

2020-06-02 09:28 UTC, ruslankhh commented on test/utils.js
> +    describe('readFile', () => {
Здесь тоже дифф криво построился. Перегруппировал тесты по функциям.

2020-06-02 09:32 UTC, ruslankhh commented on README.md
> +**Work only with hermione@>=3.5.0.**
Ждём вот этого PR:
https://github.com/gemini-testing/hermione/pull/495

2020-06-03 11:04 UTC, ruslankhh commented on lib/config.js
> +            .option('--code-grep', 'Enable hermione-test-filter plugin and run with filtering tests by their code');
Нужна консультация, возможно configparser или commander  и сам умеет парсить опцию из cli напрямую в сокращенном варианте.

2020-06-03 11:06 UTC, ruslankhh commented on lib/index.js
> +        if (pluginConfig.inputFile) {
Возможно нужно поставить значение по умолчанию для inputFile `null`, потому он становиться необязательным.

2020-06-03 11:14 UTC, ruslankhh commented on lib/index.js
> +                        testCollection.disableTest(test.fullTitle(), browserId);
В данном случае мы тупо проходим по всем тестам, и проверяем на условие фильтрации.
Даже если у нас hermione запускалась с grep или только один файл.
В `testCollection.eachTest -> test` у нас нет знаний о статусе теста, потому что он ходи по `_specs`, а не `_originalSpecs`.
https://github.com/gemini-testing/hermione/blob/master/lib/test-collection.js#L93-L101

2020-06-03 11:17 UTC, ruslankhh commented
В hermione предложили вытаскивать код hook другим способом:
https://github.com/gemini-testing/hermione/pull/495#discussion_r434483819
Если он будет утвержден, в этом PR-е нужно будет добавить вытаскивание кода из hook другим способом.

2020-06-03 18:36 UTC, ruslankhh commented on lib/index.js
> +        if (pluginConfig.inputFile) {
не буду делать так, иначе мы сломаем обратную совместимость.
Думаю, разработчики догадаются, что у них есть inputFile.

2020-06-09 14:30 UTC, DudaGod requested changes
Нужно подрефакторить и оптимизировать код. Ну и сделать так, чтобы он работал (присутствует подписка на несуществующее событие). Тесты пока не смотрел.

2020-06-09 14:30 UTC, DudaGod commented on README.md
> +* `codeFilter` **[String|RegExp|Function]** (optional) - string, regexp or function for filtering tests by their code.
Зачем в описании опции еще раз перечислять ее возможные типы? Они же указаны чуть в формате jsdoc. Плюс я бы еще написал, что по умолчанию - `null`, как в предыдущих опциях.

Может опцию назовем `filterTestsByCode`? Название чуть длинее, но как по мне понятнее, что она делает. Ну и в описании нужно явно указать, что для теста учитываются все его хуки, а не только то, что в `it` находится.

2020-06-09 14:30 UTC, DudaGod commented on README.md
> +**Work only with hermione@>=3.5.0.**
work -> work**S**
И точка после нуля лишняя

2020-06-09 14:30 UTC, DudaGod commented on README.md
> +        codeFilter: ({ value }) => {
Что еще за `value`? Почему явно не написать, что это - `testSrc` например?

2020-06-09 14:30 UTC, DudaGod commented on README.md
> +npx hermione --code-filter assertView
при вызове такой команды должно быть очевидно, что произойдет. Я бы опцию назвал `--filter-tests-by-code`. Да, она длинее, но значительно понятнее.

2020-06-09 14:30 UTC, DudaGod commented on lib/config.js
> +const parseArgs = require('yargs-parser');
для чего нам тут еще какой-то парсер?

2020-06-09 14:30 UTC, DudaGod commented on lib/config.js
> +            .option('--code-filter', 'Enable hermione-test-filter plugin and run with filtering tests by their code');
Есть же отдельная опция `enabled`, давай только она и будет включать плагин.

2020-06-09 14:30 UTC, DudaGod commented on lib/config.js
> +        }
Вместо этого кода в основном файле плагина нужно получить инстанс коммандера подписавшиться на `CLI` событие и сохранить в переменную. А затем на `INIT` получить значение опции

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +    hermione.on(hermione.events.CLI, extendCli);
подписка должна быть ниже. Если плагин не включен, то не нужно подписываться на событие `CLI`

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
>      }
давай эти if-аки в один объединим:
```
if (!pluginConfig.enabled || hermione.isWorker()) {
    return;
}
```

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +    hermione.on(hermione.events.BEFORE_TESTS_READ, (testParser) => {
такого события в hermione нет. Ты этот код еще не проверял что ли?

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +            parser.off('hook', hookCollector);
не вижу смысла здесь отписываться. У нас всего одна подписка на событие

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +            parser.on('hook', hookCollector);
если завтра мы название события поменяем? На `hook2` например. Здесь нужно брать название из поля `events` у `testParser`

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +            }
Зачем такой сложный код?
```
const f = _.isFunction(pluginConfig.codeFilter) 
  ? pluginConfig.codeFilter
  : (testCode) => new RegExp(pluginConfig.codeFilter).test(testCode);
```

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +            }
давай здесь рефакторить, эта портянка из `if else` выглядит очень плохо

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +            input.forEach(({fullTitle, browserId}) => testCollection.enableTest(fullTitle, browserId));
зачем здесь включать тесты если ты их ниже опять отключаешь? Почему не включать их в одном месте?

2020-06-09 14:30 UTC, DudaGod commented on lib/index.js
> +                        testCollection.disableTest(test.fullTitle(), browserId);
Ничего не понял, у тебя у теста должно быть поле - `disabled` по которому и можно понять отклюен тест или нет.

2020-06-09 14:30 UTC, DudaGod commented on lib/utils.js
> +        afterEach: afterEachBodies
точно ли нам нужные все эти поля?

2020-06-09 14:30 UTC, DudaGod commented on lib/utils.js
> +        value,
не очевидное название. Почему бы просто не возвращать строкой текст теста?

2020-06-09 14:30 UTC, DudaGod commented on lib/utils.js
> +        );
дублирование

2020-06-09 14:30 UTC, DudaGod commented on lib/utils.js
> +    });
Здесь не хватает оптимизации. У многих тестов будет похожее дерево сьютов с одинаковыми `beforeEach` и `afterEach`. Т.е. мы можем строить мапку с `fullTitle`-ами сьютов. А затем при совпадении у теста `fullTitle` родителя брать уже подсчитанное содержимое хуков.

2020-06-10 17:21 UTC, ruslanxdev commented on lib/config.js
> +            .option('--code-filter', 'Enable hermione-test-filter plugin and run with filtering tests by their code');
Тогда не удобно будет использовать эту опцию.
`npx hermione run --hermione-test-filter-enabled true --filter-tests-by-code assertView`
vs
`npx hermione run --filter-tests-by-code assertView`

2020-06-10 17:23 UTC, ruslanxdev commented on lib/index.js
> +    hermione.on(hermione.events.CLI, extendCli);
Тогда `--help` не будет выводить подсказку для этого плагина, когда он выключен.

2020-06-10 17:25 UTC, ruslanxdev commented on lib/index.js
> +    hermione.on(hermione.events.BEFORE_TESTS_READ, (testParser) => {
Не проверял, потому что API в hermione ещё нет. Я думал тестов хватит.
Но я могу, да, без новой версии hermione проверить.

2020-06-10 18:11 UTC, ruslanxdev commented on lib/index.js
> +            input.forEach(({fullTitle, browserId}) => testCollection.enableTest(fullTitle, browserId));
здесь я прохожу по списку из `inputFile`, у меня есть только `fullTitle` и `browserId` — я не получить здесь код теста и проверить удовлетворяет ли этот тест условию `filterTestsByCode`.

2020-06-10 18:12 UTC, ruslanxdev commented on lib/utils.js
> +        afterEach: afterEachBodies
Да, можно убрать.

2020-06-10 18:13 UTC, ruslanxdev commented on lib/utils.js
> +        value,
да

2020-06-10 18:15 UTC, ruslanxdev commented on lib/utils.js
> +        );
если ты о том, что `beforeEachBodies` и `afterEachBodies` похоже конкатинируются, то — нет, они в разном порядке добавляются.

2020-06-10 18:40 UTC, ruslanxdev commented on lib/index.js
> +                        testCollection.disableTest(test.fullTitle(), browserId);
Да, всё верно.

2020-06-11 05:51 UTC, ruslankhh commented on lib/config.js
> +const parseArgs = require('yargs-parser');
Для того, чтобы в `parseConfig` парсить опции. В этом месте у нас нет доступа к `commander`.
А в `extendCli` мы уже не можем повлиять на опции плагина.
Я попробовал разными способами, красиво не получается. А писать там костыли не очень хочется.

2020-06-11 06:01 UTC, ruslankhh commented on lib/config.js
> +        }
Мне не очень, что придется выносить работу с конфигом из `config.js`.
Я придумал другой способ, буду в `extendCli` опрокидывать `puginOptions` и там уже у меня будет доступ к `commander`. И всё останется в одном файле.

2020-06-11 06:02 UTC, ruslankhh commented on lib/config.js
> +const parseArgs = require('yargs-parser');
Придумал, как обойтись без этого парсера.

2020-06-11 12:04 UTC, ruslankhh commented on lib/utils.js
> +    });
Может быть это на потом оставим?
Это же не продовая история. Я проверю на web4 как быстро это будет работать.

2020-06-16 10:22 UTC, DudaGod requested changes
Судя по коду, плагин сейчас работает не корректно, он не получает данные своих хуков. Так же не исправлены тесты после исправлений в hermione.

2020-06-16 10:22 UTC, DudaGod commented on lib/config.js
> +            parsedOptions.enabled = true;
мне не нравится неявное включение плагина. Для чего так делать? Почему нельзя еще одну опцию явно указать?

2020-06-16 10:22 UTC, DudaGod commented on lib/config.js
> +            .option('--filter-tests-by-code', 'Enable hermione-test-filter plugin and run with filtering tests by their code');
Напомни зачем вообще отдельная опция `--filter-tests-by-code`? Почему не использовать явно через `--hermione-test-filter`?

2020-06-16 10:22 UTC, DudaGod commented on lib/config.js
> +        const { filterTestsByCode } = parseArgs(argv.slice(2), { string: ['filter-tests-by-code'] });
можно было бы просто из `argv` достать интересующее поле. Ну либо заюзать парсер коммандера, мне не нравится, что у нас плодится количество парсеров.

2020-06-16 10:22 UTC, DudaGod commented on lib/index.js
> +        const typeHook = hook.title.includes('before') ? 'beforeEach' : 'afterEach';
а зачем тут `includes`? У нас же только два хука может быть. Либо `beforeEach`, либо `afterEach`

2020-06-16 10:22 UTC, DudaGod commented on lib/index.js
> +    let hookCollector = (hook) => {
Почему бы не вынести логику по работе с построением `body` теста в отдельный класс? В котором будет инкапсулирована логика по работе с хуками, тестами и прочим. Сейчас у тебя это размазано между основным файлом плагина и утилитами.

2020-06-16 10:22 UTC, DudaGod commented on lib/utils.js
> +    const suiteHooks = hookCollection[`${suite.parent.fullTitle()} (${browserId})`] || {};
у тебя же этот код сейчас не работает. Ты пытаешься достать хуки с указанием `fullTitle` + `browserId`. А складываешь их изначально только по `fullTitle`.

И я не понял для чего ты тут пытаешься `browserId` юзать.

2020-06-16 10:22 UTC, DudaGod commented on lib/utils.js
> +    if (test.body) testBodies.push(test.body);
давай писать с фигурными скобками. К сожалению  у нас на это правило eslint пока нет

2020-06-16 10:22 UTC, DudaGod commented on test/index.js
> +    const mkTestParser = () => {
Это не валидный стаб и судя по коду ниже ты тесты не поправил. Давай, поправим.

2020-06-16 10:22 UTC, DudaGod commented on test/utils.js
> +            assert.containsAllKeys(getTestCode(test, hookCollection), ['value', 'beforeEach', 'test', 'afterEach']);
таких полей тоже уже нет

2020-06-30 10:39 UTC, ruslankhh commented on lib/config.js
> +            parsedOptions.enabled = true;
Мы явно включаем плагин с помощью опции. Одна опция нужна для удобства.
`npx hermione run --hermione-test-filter-enabled true --filter-tests-by-code assertView`
vs
`npx hermione run --filter-tests-by-code assertView`
Хочу использовать решение, как здесь:
https://github.com/gemini-testing/hermione-test-repeater/blob/master/lib/index.js#L20

2020-06-30 10:39 UTC, ruslankhh commented on lib/config.js
> +            .option('--filter-tests-by-code', 'Enable hermione-test-filter plugin and run with filtering tests by their code');
Ответил выше.

2020-06-30 10:40 UTC, ruslankhh commented on lib/config.js
> +        const { filterTestsByCode } = parseArgs(argv.slice(2), { string: ['filter-tests-by-code'] });
Коммандер не получается нормально заиспользовать.
Но я могу взять решение отсюда:
https://github.com/gemini-testing/hermione-test-repeater/blob/master/lib/index.js#L27

2020-06-30 10:42 UTC, ruslankhh commented on lib/index.js
> +        const typeHook = hook.title.includes('before') ? 'beforeEach' : 'afterEach';
Нужно, чтобы отличать beforeEach от afterEach хуков.
Там в tilte `"before each"` либо `"after each"`, beforeAll и afterAll на уровне hermione игонряться, так что я не учитываю их здесь.

2020-06-30 10:43 UTC, ruslankhh commented on lib/utils.js
> +    const suiteHooks = hookCollection[`${suite.parent.fullTitle()} (${browserId})`] || {};
Перепроверю, возможно где-то недоглядел.

`browserId` нужне для того, чтобы тесты с одним названием из разных файлов для разных платформ/браузеров не перетерли хуки в коллекции.

2020-06-30 10:43 UTC, ruslankhh commented on test/index.js
> +    const mkTestParser = () => {
тесты ещё не правил, сорян.

2020-06-30 10:44 UTC, ruslankhh commented on test/utils.js
> +            assert.containsAllKeys(getTestCode(test, hookCollection), ['value', 'beforeEach', 'test', 'afterEach']);
тесты ещё не правил, сорян.

2020-07-03 14:22 UTC, ruslankhh commented
Переделал объект `hookCollection` в класс `testCodeCollection`, перенес в него всю работу с кодом тестов.
В `testCodeCollection` отказался от `'${fullTiltle} (${browserId})'` в пользу `crypto.createHash('md5')` по `fullTitle + ' ' + filePath`. Так как при записи `hook` в коллекцию у них нет `browserId`, и c `browserId` в коллекции будет слишком много дублей.
Проверил на web4 всё работает.

2020-07-11 13:03 UTC, DudaGod requested changes
С тестами все плохо =(

2020-07-11 13:03 UTC, DudaGod commented on lib/test-code-collection.js
> +        let suite = runnable;
почему suite? Ты же передаешь сюда и test еще

2020-07-11 13:03 UTC, DudaGod commented on lib/test-code-collection.js
> +    get(fullTitle, filePath) {
по названию данного метода непонятно, что он делает

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +
зачем тут две пустые строки?

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                const test = _collection.find((test) => test.title === fullTitle);
в тестах такую логику писать не принято. Почему нельзя данные метод просто заспаить с помощью `sinon.spy`?

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                    return tests.find((test) => test.title === fullTitle).body;
зачем? Тут просто `returns` должен быть в зависимости от полученных аргументов

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +            afterEach(() => sinon.restore());
у тебя в начале файле уже есть afterEach с очисткой. Зачем еще один? И тут же `sandbox.stub` в файле юзается. Либо давай везде его юзать, либо перепишем на `sinon.stub`, чтобы консистентно было.

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                hermione.emit(hermione.events.BEFORE_TESTS_READ, {testParser});
такого события в hermione нет

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                assert.calledTwice(testParser.on);
Тут правильнее было бы явно проверить на какие события должен подписаться testParser. А так же написать тест, что при их эмите сработает `testCodeCollection.add`

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                assert.calledOnce(testCollection.disableTest);
Где аргументы у вызова `disableTest`?

У тебя тесты не самодостаточны, куча логики происходит в `beforeEach`. Из-за этого ты в каждый тест принес комментарий. От него можно легко избавится если неважную логику для теста унести в хелперу, а важную прокидывать через аргументы

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                // we should disable 'title1' and 'title3'
Почему эту информацию не указать явно в проверках с чем вызывался `disableTest`?

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +            });
в этом и предыдущем тесте логика абсолютна одинаковая кроме указания `filterTestsByCode`. Это говорит о том, что тут можно использовать `forEach`, чтобы избавится от дублирования.

2020-07-11 13:03 UTC, DudaGod commented on test/index.js
> +                // we should disable 'title1' only, without 'title3', not how we did last time
по коду теста должно быть понятно, что в нем происходит без каких либо комментариев. Сейчас у тебя не так по следующим причинам:
- куча логики использующейся в тесте находится в `beforeEach`
- вызовы методов проверяются без каких либо аргументов

2020-07-11 13:03 UTC, DudaGod commented on test/test-code-collection.js
> +                this.counter++;
такой логики в тестах быть не должно

2020-07-11 13:03 UTC, DudaGod commented on test/test-code-collection.js
> +            assert.lengthOf(_.keys(testCodeCollection._collection), 2);
тесты должны быть написаны по принципу - `arrange -> act -> assert`. А у тебя тут все в перемешку и без какой либо группировки

2020-07-11 13:03 UTC, DudaGod commented on test/test-code-collection.js
> +            sinon.stub(testCodeCollection, 'get')
стабы должны выполняться до создания инстанса

2020-07-11 13:03 UTC, DudaGod commented on test/test-code-collection.js
> +            assert.equal(testCodeCollection._getRunnableCode(hook), HOOK_BODY);
приватные методы тестировать нельзя

2020-09-01 15:25 UTC, ruslankhh commented on test/test-code-collection.js
> +            sinon.stub(testCodeCollection, 'get')
Сделал вот так:
```js
sinon.stub(TestCodeCollection.prototype, '_getItem')
    .withArgs(TEST_NAME, FILE_PATH).returns(testItem)
    .withArgs(SUITE_NAME, FILE_PATH).returns(suiteItem);
sinon.stub(TestCodeCollection.prototype, '_getHookStackCode').returns({beforeEachCode: HOOK_BODY});

testCodeCollection = new TestCodeCollection({
    [testItemId]: testItem,
    [suiteItemId]: suiteItem
});
```

2020-09-01 17:32 UTC, ruslankhh commented on lib/index.js
> +        hermione.on(hermione.events.BEFORE_FILE_READ, ({testParser, testCodeCollection}) => {
Вот тут я не уверен, насколько корректно так пробрасывать стаб `testCodeCollection`, но ничего другого я не придумал.

2020-09-03 06:50 UTC, DudaGod reviewed
Давай хак с `testCodeCollection` поправим и вольем. Нужно всего лишь `proxyquire` заюзать для этого. Примеры использования можешь посмотреть в той же hermione например.

2020-09-03 06:50 UTC, DudaGod commented on lib/index.js
> +        hermione.on(hermione.events.BEFORE_FILE_READ, ({testParser, testCodeCollection}) => {
Что-то я не понял, откуда у тебя здесь `testCodeCollection`? Гермиона же на событие `BEFORE_FILE_READ` не кидает его. Это ты реализовал что ли для тестов? Это не правильное решение =(

Судя по твоим тестам тебе нужно просто заиспользовать библиотеку `proxyquire`, чтобы подменить `require('./test-code-collection')` на свой стаб и все.

2020-09-03 06:50 UTC, DudaGod commented on lib/index.js
> +            if (filterTestsByCode) {
почему бы не инвертировать условие и не уменьшить вложенность кода?
Можно же написать:
```
if (!filterTestsByCode) {
  return;
}
// your code without extra nesting
```

2020-09-03 06:50 UTC, DudaGod commented on lib/index.js
> +            if (filterTestsByCode) {
тут я бы тоже инвертировал условие

2020-09-03 11:04 UTC, DudaGod approved these changes
/ok

2020-09-03 11:05 UTC, merged